# -------------------------
# Jekyll configs
# -------------------------
source: src
destination: dist
timezone: America/New_York

# -------------------------
# Site variables available to liquid templates
# -------------------------
title: Site Title
description: Site Description
favicon: http://res.cloudinary.com/l9tl/v1472846223/identity/short-logo.png
telephone: 617.286.6135
emails:
  info: info@9tailors.com
  customerservice: customerservice@9tailors.com
  weddings: weddings@9tailors.com

# -------------------------
# Cloudcannon global editor options
# -------------------------
_options:
  content:
    # format: p h1 h2 h3 h4 h5 h6 pre address div
    format: p h1 h2 h3
    undo: true
    redo: true
    bold: true
    italic: true
    removeformat: true
    underline: true
    blockquote: true
    strike: true
    link: true
    image: true
    # styles: /cloudcannon/content.css

# -------------------------
# Collections
# -------------------------
collections:
  pages:
    output: true
  gallery:
    output: true

# -------------------------
# Collection default settings
# -------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _gallery
    values:
      layout: gallery
    # _comments:
    #   title: Post title

# -------------------------
# kramdown settings
# -------------------------
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  # handle ellipsis
